const test=require('node:test'),assert=require('node:assert/strict'),vm=require('node:vm'),fs=require('node:fs'),path=require('node:path')
function service(modal=async()=>({confirm:true})){let sent=[];const ctx={module:{exports:{}},require:id=>id.includes('config')?{aiFunction:'test'}:{callNative:modal},wx:{cloud:{callFunction:async args=>{sent.push(args);return {result:{ok:true,text:'点评'}}}}},Date};vm.runInNewContext(fs.readFileSync(path.join(__dirname,'../miniprogram/services/ai.js'),'utf8'),ctx);return {ai:ctx.module.exports,sent,ctx}}
test('key only held in memory, validates format and clears',()=>{const {ai}=service();assert.equal(ai.isReady(),false);assert.throws(()=>ai.setKey('sk-test\nheader'));ai.setKey('sk-'+'x'.repeat(32));assert.equal(ai.isReady(),true);ai.clearKey();assert.equal(ai.isReady(),false)})
test('vision is default and selected model is sent unchanged',async()=>{const {ai,sent}=service();ai.setKey('sk-'+'x'.repeat(32));assert.equal(await ai.generate('p_1','photo'),'点评');assert.equal(sent[0].data.model,'deepseek-v4-flash-vision-exp');assert.equal(await ai.generate('p_1','photo'),'点评');assert.equal(sent.length,2)})
test('text model is blocked before network without fallback',async()=>{const {ai,sent}=service();ai.setKey('sk-'+'x'.repeat(32));ai.setModel('deepseek-v4-pro');await assert.rejects(ai.generate('p_1','photo'),/仅支持文本/);assert.equal(sent.length,0);assert.throws(()=>ai.setModel('unknown'))})
test('provider or cloud diagnostic messages are never reflected',async()=>{const {ai,ctx}=service();ai.setKey('sk-'+'x'.repeat(32));ctx.wx.cloud.callFunction=async()=>{throw new Error('API Key SECRET')};await assert.rejects(ai.generate('p_1','photo'),e=>!e.message.includes('SECRET'))})
const {mime}=require('../cloudfunctions/lab06_aiReview/safe-http')
test('image bytes validated independent of filename',()=>{assert.equal(mime(Buffer.from([255,216,255])),'image/jpeg');assert.throws(()=>mime(Buffer.from('<html>error</html>')))})

test('known failure before provider permits immediate retry',async()=>{const {ai,ctx}=service();let attempts=0;ai.setKey('sk-'+'x'.repeat(32));ctx.wx.cloud.callFunction=async()=>{attempts++;return {result:attempts===1?{ok:false,code:'IMAGE'}:{ok:true,text:'ok'}}};await assert.rejects(ai.generate('p_1','photo'),/未发送/);assert.equal(await ai.generate('p_1','photo'),'ok');assert.equal(attempts,2)})

test('only an unfinished request blocks the next request',async()=>{const {ai,ctx}=service();ai.setKey('sk-'+'x'.repeat(32));let finish;ctx.wx.cloud.callFunction=()=>new Promise(resolve=>{finish=resolve});const first=ai.generate('p_1','photo');await Promise.resolve();await assert.rejects(ai.generate('p_1','photo'),/上一条/);finish({result:{ok:true,text:'first'}});assert.equal(await first,'first');ctx.wx.cloud.callFunction=async()=>({result:{ok:true,text:'next'}});assert.equal(await ai.generate('p_1','photo'),'next')})
test('transport failure releases lock without waiting',async()=>{const {ai,ctx}=service();ai.setKey('sk-'+'x'.repeat(32));ctx.wx.cloud.callFunction=async()=>{throw new Error('test')};await assert.rejects(ai.generate('p_1','photo'));ctx.wx.cloud.callFunction=async()=>({result:{ok:true,text:'retry'}});assert.equal(await ai.generate('p_1','photo'),'retry')})

test('confirmation cancellation and failure both release pending lock',async()=>{let n=0;const {ai}=service(async()=>{n++;if(n===1)throw new Error('cancelled dialog');return {confirm:n!==2}});ai.setKey('sk-'+'x'.repeat(32));await assert.rejects(ai.generate('p_1','photo'));assert.equal(await ai.generate('p_1','photo'),null);assert.equal(await ai.generate('p_1','photo'),'点评')})
test('pending confirmation blocks a second dialog',async()=>{let close,n=0;const {ai}=service(()=>{n++;return new Promise(resolve=>{close=resolve})});ai.setKey('sk-'+'x'.repeat(32));const first=ai.generate('p_1','photo');await assert.rejects(ai.generate('p_1','photo'),/上一条/);assert.equal(n,1);close({confirm:false});assert.equal(await first,null)})
